version: "3.8"

services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"

    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
